# fly.toml app configuration file generated for holy-rosary on 2024-11-02T13:24:48+06:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'holy-rosary'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
